### ISSUE TITLE
Unable to connect to PostgreSQL: SSL is commented out in postgresql_driver.dart

### ISSUE THREAD

**Issue by Shazin12** [vania-dart/framework#118]
I am unable to connect to my PostgreSQL database using the PostgreSQLDriver in Dart. It appears that the SSL configuration is commented out in the code, which prevents secure connections to the database.

i think this is the issue causing to connect to ssl required database
//'sslmode': env<bool>('DB_SSL_MODE',true) == true  ? 'require' : '',
![Screenshot 2024-08-24 124831](https://github.com/user-attachments/assets/94df4fd6-50f9-4978-8f01-7e18e8da3612)

**Comment by javad-zobeidi** [comment]
i will check this

**Comment by javad-zobeidi** [comment]
Please upgrade to the latest version
