### ISSUE TITLE
[BUG] -when websocket connect , Error reporting: failed: Error during WebSocket handshake: Unexpected response code: 200

### ISSUE THREAD

**Issue by zhou26192619** [vania-dart/framework#120]
create default project . when websocket connect , Error reporting: failed: Error during WebSocket handshake: Unexpected response code: 200 . 
Also, I do not see the function of deploying static files in the document.

**Comment by javad-zobeidi** [comment]
@zhou26192619 
Did you enable the web socket in the `.env` file?

For static files, you need to put them in the public folder

```shell

public\folder\file.jpg 
public\folder\html.index

// access

HTTP://domian.com/folder/file.jpg

```

**Comment by zhou26192619** [comment]
> @zhou26192619 Did you enable the web socket in the `.env` file?
> 
> For static files, you need to put them in the public folder
> 
> ```shell
> public\folder\file.jpg 
> public\folder\html.index
> 
> // access
> 
> HTTP://domian.com/folder/file.jpg
> ```

thank you .
