### ISSUE TITLE
[BUG] - Problem migrating on database(id column)

### ISSUE THREAD

**Issue by WellingtonNico** [vania-dart/framework#127]
**Describe the bug**
When running migrate in postgres database, the id column is not created with auto increment option, so when trying to create an object with ORM an error raises on postgres and its not thrown in dart, i think an exception should occur but the code keeps running like there was no error.

**To Reproduce**
this is my controller:
```dart
import 'package:tutorial/app/models/user.dart';
import 'package:vania/vania.dart';

class AuthController extends Controller {
  Future<Response> register(Request request) async {
    final name = request.input('name');
    final email = request.input('email');
    var password = request.input('password');

    print(name);
    print(email);
    print(password);

    request.validate({
      'name': 'required',
      'email': 'required|email',
      'password': 'required|min_length:8',
    }, {
      'name.required': 'Este campo é obrigatório.',
      'name.string': 'O nome precisa ser um texto.',
      'name.alpha': 'O nome não pode conter números.',
      'email.required': 'Este campo é obrigatório.',
      'email.email': 'Email inválido.',
      'password.required': 'Este campo é obrigatório.',
      'password.string': 'A senha precisa ser um texto.',
      'password.min_length': 'A senha precisa ter no mínimo 8 caracteres.',
    });

    final user = await User().query().where('email', '=', email).first();
    if (user != null) {
      return Response.json({'email': 'Email já cadastrado.'}, 400);
    }

    password = Hash().make(password);

    User().query().create({
      "name": name,
      "email": email,
      "password": password,
      "created_at": DateTime.now(),
      "updated_at": DateTime.now()
    });

    return Response.json({"message": "Usuário registrado com sucesso!"}, 201);
  }
}
final AuthController authController = AuthController();
```

this is my user migration
```dart
class CreateUserTable extends Migration {
  @override
  Future<void> up() async {
    super.up();
    await createTableNotExists('users', () {
      id();       
      char('name', length: 100);
      char('avatar', length: 250,nullable: true);
      char('password', length: 200);
      char('email', length: 60);
      char('phone', length: 60,nullable: true);
      text('description',nullable: true);
      date('birthday',nullable: true);
      timeStamp('created_at');
      timeStamp('updated_at');
    });
  }
  @override
  Future<void> down() async {
    super.down();
    await dropIfExists('users');
  }
}
```

**Expected behavior**
The user line should be created or an error should be raised when there is a database error.

**Environment:** 
- Dart Version: 3.4.3
- Vania Version: 0.4.1
- Operating System: mac sequoia
- Database: PostgreSQL 14
- Any other relevant backend services or middleware

**Additional context**
Remind the column was created without incremental id.

**Logs**
PostgreSQLSeverity.error 23502: null value in column "id" of relation "users" violates not-null constraint

**Comment by javad-zobeidi** [comment]
I will checking and fix this thank you for report

**Comment by javad-zobeidi** [comment]
Please upgrade to the latest version

* you need to run the `vania migration` command again

**Comment by WellingtonNico** [comment]
> Please upgrade to the latest version
> 
> * you need to run the `vania migration` command again

Great, everything is working now!

Plus i have some questions:
* How can i set a column as unique in the migrations, like email or document numbers?
* How can i configure vscode tu debug using "vania serve" command? I tryied this config but it didn't work:
```json
 {
      "name": "Serve",
      "type": "dart",
      "request": "launch",
      "args": ["serve"],
      "program": "/Users/wellington/.pub-cache/bin/vania",
 }
```

update:
My password column as you could see can hold up to 200 chars, i noticed a problem verifying hash, it was returning false, and i was using postman to test, so the password is correct, i triyed many times and found out the problem: even trying to use .trim() method in the Hash().make(password), in the database the result is saved with the full length, like the hash had only 92 chars, and this is why my login funcion was not working, so there might another point you should take care, and may be this problem occurs only with postgres

**Comment by WellingtonNico** [comment]
Another error with postgres, although the table was created correctly:

<img width="744" alt="image" src="https://github.com/user-attachments/assets/e1b0fd4c-cb4e-4e4d-891f-11bfafabb686">


**it returns in my login function:**
```json
{
    "message": "PostgreSQLSeverity.error : Could not infer type of value '9be7cb96075a0bd558514b7a026d72c2'. "
}
```

**this is my token table migration:**
```dart
import 'package:vania/vania.dart';

class CreatePersonalAccessTokensTable extends Migration {
  @override
  Future<void> up() async {
    super.up();
    await createTableNotExists('personal_access_tokens', () {
      id();
      char('name', length: 60);
      bigInt('tokenable_id');
      char('token', length: 255);
      timeStamp('created_at');
    });
  }

  @override
  Future<void> down() async {
    super.down();
    await dropIfExists('personal_access_tokens');
  }
}
```

**this is my login function:**
```dart
Future<Response> login(Request request) async {
    request.validate({
      'email': 'required|email',
      'password': 'required|min_length:8',
    }, {
      'email.required': 'Este campo é obrigatório.',
      'email.email': 'Email inválido.',
      'password.required': 'Este campo é obrigatório.',
      'password.string': 'A senha precisa ser um texto.',
      'password.min_length': 'A senha precisa ter no mínimo 8 caracteres.',
    });

    final email = request.input('email');
    final password = request.input('password');

    final user = await User()
        .query()
        .select(['id', 'name', 'email', 'password'])
        .where('email', '=', email)
        .first();

    if (user == null ||
        !Hash().verify(password, (user['password'] as String).trim())) {
      return Response.json({
        'message': 'Não foi possível fazer login com as credenciais informadas.'
      }, 400);
    }

    final auth = Auth().login(user);
    final token = await auth.createToken();

    print(token);

    return Response.json({
      'message': 'Login realizado com sucesso!',
      "token": token,
    }, 200);
  }
```

**I reproduced the equivalent query in sql just to check if there was a problem in my postgres database, but it worked normally. Follow the query:**
```sql
insert into
    personal_access_tokens (
        name,
        tokenable_id,
        token,
        created_at
    )
values (
        'default',
        1,
        '9be7cb96075a0bd558514b7a026d72c2',
        '2024-09-23 01:40:00.389751'
    )
```

**Comment by javad-zobeidi** [comment]
> How can i set a column as unique in the migrations, like email or document numbers?

You can use ` index`

```dart

await createTableNotExists('users', () {
      id();
      string('name');
      string('email');
      timeStamps();

      index(ColumnIndex.unique, 'email', ['email']);
    });

```




> * How can i configure vscode tu debug using "vania serve" command? I tryied this config but it didn't work:

> Another error with postgres, although the table was created correctly:


I will check

**Comment by WellingtonNico** [comment]
the main problems were solved!
I opened a new issue to keep it clean for you guys about the other problems.
