### ISSUE TITLE
[Feature Request] - Multi-language support

### ISSUE THREAD

**Issue by hxhgzz** [vania-dart/framework#141]
That's great! Are there any plans to add multi-language capability?

### Necessity

1. **User base** :
   * If your app targets a global market, supporting multiple languages will significantly improve user experience and scalability.
2. **Regulations and Compliance** :
   * In some countries and regions, providing local language support may be a legal requirement.
3. **Competitive advantage** :
   * Providing multi-language support can make your application more competitive in the market, especially in today's globalized world.

### Benefits

1. **User Experience** :
   * Users prefer to interact in a language they understand, which can increase user satisfaction and engagement.
2. **Scalability** :
   * The i18n module makes it easier to add new languages in the future without major refactoring of the application.
3. **Market Opportunities** :
   * Supporting multiple languages can open up new markets and increase the number of potential users.

### Implementation Considerations

1. **Technical Complexity** :
   * Implementing an i18n module requires some technical investment, including text translation, date and time formatting, number formatting, currency symbols, etc.
2. **Translation and Maintenance** :
   * Maintaining and updating translated content may require additional resources.
3. **Performance** :
   * The i18n module may have some impact on performance, especially when working with large amounts of translated content.

**Comment by javad-zobeidi** [comment]
@hxhgzz Update to Version 0.6.0 

[Localization](https://vdart.dev/docs/the-basics/localization)
