### ISSUE TITLE
[Feature Request] - How can I manage the 404 route?

### ISSUE THREAD

**Issue by H3mnz** [vania-dart/framework#145]
I want to display a static file instead of the Not Fount 404 text

**Comment by javad-zobeidi** [comment]
Update To last version (^0.6.2)

   - To enable this feature, create an `errors` directory in the root of the project.
   - Inside the `errors` directory, create a `404.html` file at `errors/404.html`.
   
**Errors directory placement:**
```
-lib
- errors
  --- 404.html
```
