### ISSUE TITLE
validating file

### ISSUE THREAD

**Issue by Ehsan-abaci** [vania-dart/framework#16]
Hi. I use validating for file as below line without "required". But it doesn't let me to send a req without filling the file.
actually it returns error for this.
![Screenshot 2024-03-07 140333](https://github.com/vania-dart/framework/assets/131594744/1e85c296-04e3-434b-8790-ba1b9f3df43b)

**Comment by javad-zobeidi** [comment]
Thank you for reporting please update vania to 0.1.1+4
