### ISSUE TITLE
Can't deploy on render.com

### ISSUE THREAD

**Issue by D3R50N** [vania-dart/framework#29]
When trying to deploy on render.com, have this isses 
`Exception: Key not found
#0      Application.initialize (package:vania/src/application.dart:20)
#1      main (file:///www/bin/server.dart:5)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
#3      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)`

I don't really know why but i think it because render.com has a built-in section for env variables that I filled but it seems Vania needs (somehow) the .env file to load env variables. So I pushed the .env file (I wish I wouldn't..), and I retry to deploy, but same issue. 

So I don't really know how vania works but by reading the source code, it's obvious the env var 'APP_KEY' can't be found and the only reason that explain it is that the .env file is not loaded.

Please help.

![image](https://github.com/vania-dart/framework/assets/67974781/c5f06a57-a327-47b9-973a-c89dc7cfea3f)
![image](https://github.com/vania-dart/framework/assets/67974781/9c5e2169-1741-49bc-81c3-782aaefcc4c1)

**Comment by D3R50N** [comment]
BTW render.com supports Docker.

**Comment by javad-zobeidi** [comment]
I'll be checking this

**Comment by javad-zobeidi** [comment]
In your project update Vania to the latest version (current is 0.1.7+1) and try again

**Comment by D3R50N** [comment]
OK, I'll try

**Comment by D3R50N** [comment]
Hello. I tried another deploy with version 0.1.7+1; it seems .env is loaded but I still get another error.

![image](https://github.com/vania-dart/framework/assets/67974781/74800c7e-dd6c-48b7-b716-b4ccdeb5be6e)

As you can see below, it's an issue from .env. It seems some booleans can't be parsed. The issue come from this line in your package.
` if (T.toString() == 'bool') {
      return bool.parse(value.toString()) as T;
    }`

When I look at the .env I can't see any 'wrong' boolean and the logs don't show exactly with values are concerned. So idk what I can do at this step.

**Comment by D3R50N** [comment]
I've fixed this by a adding some missing keys in .env. 
Explained in this new issue #40
