### ISSUE TITLE
Syntax error with index keyword in PostgreSQL query using vania migrate

### ISSUE THREAD

**Issue by prosperouscad-ux** [vania-dart/framework#30]
I'm encountering a syntax error when using the index keyword in a PostgreSQL query. Specifically, I receive the following error message: "PostgreSQLSeverity.error 42601: syntax error at or near 'index'". This occurs when attempting to create or modify an index in my database.

**Proposed Solution**
I believe the issue is how the join of the indexes list is being constructed.

**Additional Information**
it actually works if I execute the sql query directly using pgAdmin.
Like for example, making the email column unique, it works when I execute directly using pgAdmin 
but gets the above problem when I use the framework.

**Screenshots**
![Screenshot 2024-04-18 at 11 59 26 AM](https://github.com/vania-dart/framework/assets/60725465/8bd32009-be37-41fd-bd26-372a996585d0)

![Screenshot 2024-04-18 at 11 55 31 AM](https://github.com/vania-dart/framework/assets/60725465/c0253478-d72c-4386-8cfe-b533cd98644f)

![Screenshot 2024-04-18 at 12 00 41 PM](https://github.com/vania-dart/framework/assets/60725465/171558d4-699c-4adc-a50e-5d1f86b8ae9d)

**Comment by prosperouscad-ux** [comment]
Using the enum ColumnIndex.indexKey works but the ColumnIndex.unique doesn't work because using UNIQUE INDEX is syntactically incorrect in SQL. some database allows UNIQUE INDEX, others do not and its also not part of the core SQL standard.

**Comment by javad-zobeidi** [comment]
@prosperouscad-ux Thank you for reporting
I'll be fixing this

**Comment by prosperouscad-ux** [comment]
Sure. Thank you!

**Comment by javad-zobeidi** [comment]
@prosperouscad-ux Yes sure, if you can make PR

**Comment by javad-zobeidi** [comment]
Please update to 0.1.7+4 and test

**Comment by iamtoricool** [comment]
![image](https://github.com/vania-dart/framework/assets/95972672/a41b4e41-f05e-4a0c-b8ee-849c04feb938)
The issue exists in the latest version of vania. @javad-zobeidi

**Comment by javad-zobeidi** [comment]
@iamtoricool Please update to the last version 0.2.1 and test it
