### ISSUE TITLE
Unable to create project following the documentation

### ISSUE THREAD

**Issue by sudophils** [vania-dart/framework#32]
Creating a "Vania/Dart" project at "./todo"
Unhandled exception:
PathNotFoundException: Directory listing failed, path = '/Users/xxx/Desktop/Project/dart-api/todo/' (OS Error: No such file or directory, errno = 2)
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:233:5)
#2      NewProject.execute (package:vania_cli/commands/new_project.dart:40:33)
#3      CommandRunner.run (package:vania_cli/commands/command_runner.dart:71:13)
#4      main (file:///Users/champ/.pub-cache/hosted/pub.dev/vania_cli-0.0.7+1/bin/vania_cli.dart:4:19)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

**Comment by javad-zobeidi** [comment]
@sudophils First update Vania cli with `vania update`

Which OS you are using?
