### ISSUE TITLE
"vania serve" error on new project

### ISSUE THREAD

**Issue by ruwiss** [vania-dart/framework#33]
![image](https://github.com/vania-dart/framework/assets/115001323/b003990f-bbb4-4ba1-8b2e-9287c0c21ea3)

**Comment by javad-zobeidi** [comment]
It's related to pointycastle package

What is your Dart SDK version

**Comment by ruwiss** [comment]
Dart SDK version: 3.3.4 (stable)

**Comment by javad-zobeidi** [comment]
It's related to pointycastle package

please do this

1) go to this path `\AppData\Local\Pub\Cache\hosted\pub.dev` find pointycastle-3.9.0 and delete it 

2) put this in your pubspec

```yml
dependency_overrides:
  pointycastle: 3.7.3
```

3) run this command

```shell
dart pub get
```

and wait to update `pointycastle` to the new version

**Comment by ruwiss** [comment]
It's worked! Congratulations for your project
🤍
