### ISSUE TITLE
Missing env keys since 0.1.7+1

### ISSUE THREAD

**Issue by D3R50N** [vania-dart/framework#40]
Hello. Lastly I opened an issue #29 and it was about .env not loaded. When you fixed it, I can't anymore run the project locally (neither deploy in prod). It still giving errors like this
`Unhandled exception:
FormatException: Invalid boolean
null`.

So I modified directly your package (this file [src/env_handler/env.dart](https://github.com/vania-dart/framework/tree/dev/lib/src/env_handler/env.dart)) and I've found there were some missing keys in the old generated .env :

```
APP_SECURE=false
APP_CERTIFICATE=''
APP_PRIVATE_KEY=''
APP_PRIVATE_KEY_PASSWORD=''
```

I don't really know what kind of values I can pass, but it seems :
`APP_SECURE` is a boolean. When `true`, you should provide the 3 others one.
`APP_CERTIFICATE` a path maybe ?
`APP_PRIVATE_KEY` also a path ?
`APP_PRIVATE_KEY_PASSWORD` just a string.

So, I'm creating this issue to notice and help fix.
- **Provide null safety values** 
(When a .env key is null, you should provide a default value instead of throwing an error. When I delete APP_PORT key in prod, it should use the platform environnement port but your var is name APP_PORT and not PORT. So I have to provide manually this value or else I get a null exception)
- **Update your online documentation** (first thing to do when update a package.)
- **Update template when generating new project** (like the default .env)
- **Show more relevant issues logs** (I had to modify your package before find all of this)

Waiting for your updates :)

**Comment by javad-zobeidi** [comment]
1) The `env` method allows you to pass a default value, but I will certainly update it to include some default values.
I wanted the `APP_PORT` to be the same in both the `.env` file and platform environments to avoid confusion for developers who are not familiar with the backend.
2) I will update the documentation.
3) The template has been updated and includes all the necessary environment settings.
4) Please use the latest version.

5) If possible, could you create a guide in the deploying section for [Render](https://render.com/)?

Thank you for the explanation.

**Comment by D3R50N** [comment]
Okay.
Of course. Should I write it in comment of this issue ?

**Comment by javad-zobeidi** [comment]
For doc use this repo  https://github.com/vania-dart/documentation

Make a fork and then PR

**Comment by D3R50N** [comment]
It's done. Check the [pull request.](https://github.com/vania-dart/documentation/pull/2).
