### ISSUE TITLE
[BUG] - Returning Insert To Database Is Nothing

### ISSUE THREAD

**Issue by alirezat66** [vania-dart/framework#71]
**Describe the bug**
When you insert a data on database, we got nothing 
`final result = await TaskList().query().insert({
      'title': request.input('title'),
      'user_id': Auth().id(),
      'created_at': DateTime.now(),
      'updated_at': DateTime.now(),
      'background_color': request.input('background_color', null),
    });

    return Response.json(
        {"message": "Task list created successfully", "data": result});`
then you see:

**Expected behavior**

**Screenshots**
`{
    "message": "Task list created successfully",
    "data": []
}`
**Environment (please complete the following information):** 
- Dart Version: [e.g. 3.4.0]
- Vania Version: [e.g. 0.2.6]
- Operating System: [Mac]
- Database: [MySQL]

**Comment by javad-zobeidi** [comment]
Actually, this is not a bug
The data is stored correctly in the database. To get the data you need to use insertGetId, again get the data by the ID with first

**Comment by javad-zobeidi** [comment]
Add to version 0.3.2 now you can use the `create` method

https://vdart.dev/docs/eloquent-orm/eloquent/#create-and-return-inserted-data
