### ISSUE TITLE
[Feature Request] - Allow for column to be unique in migration

### ISSUE THREAD

**Issue by PhillipMwaniki** [vania-dart/framework#76]
**Is your feature request related to a problem? Please describe.**
When designing some tables i.e. a users table, I do need the email column, and other columns, say phone_number to be unique. 

The present documentation for migration doesn't have this. We also don't have this in the code as I have tried.

**Describe the solution you'd like**
I would like it be 
```dart
string('email').unique();
```

**Describe alternatives you've considered**
Another school of thought is using of class attributes
```dart
string('email', unique: true);
```

**Additional context**
<img width="482" alt="image" src="https://github.com/vania-dart/framework/assets/2037708/7d5d738a-4b1a-44af-bf5b-a883a187330f">

**Comment by javad-zobeidi** [comment]
This already exists

You can use `index` ex:

```dart
index(ColumnIndex.unique, 'email', ['email']);
```

Table code

```dart
 Future<void> up() async {
    super.up();
    await createTable('users', () {
      id();

      string('email');

      index(ColumnIndex.unique, 'email', ['email']);
    });
  }
```

**Comment by PhillipMwaniki** [comment]
Interesting. Thank you for the suggestion.
