### ISSUE TITLE
[BUG] - Trying to set column uuid as primary key

### ISSUE THREAD

**Issue by tiagualvs** [vania-dart/framework#88]
I'm trying to set a column uuid('id') as primary key passing primary('id') below the uuid line but nothing happens, I tried to put the primary method at the final, at the begining, above and below my uuid method but as I'm say nothing happens, am I making something wrog?

```dart
await createTable('tb_users', () {
  uuid('id', defaultValue: 'uuid_generate_v4()');
  primary('id');
  string('name', length: 255);
  string('username', length: 24);
  string('email', length: 255);
  string('password', length: 255);
  string('image', nullable: true, length: 255);
  string('bio', nullable: true, length: 255);
  string('website', nullable: true, length: 255);
  timeStamp('created_at', defaultValue: 'now()');
  timeStamp('updated_at', defaultValue: 'now()');
});
```

**Comment by javad-zobeidi** [comment]
Update to V0.3.3 and try

**Comment by tiagualvs** [comment]
it worked, but now the uuid method create a char type column without defaultValue parameter, is it right?

**Comment by javad-zobeidi** [comment]
it's ok
